commodity_map = {
    "--Select--": "0",
    "Absinthe": "451",
    "Ajwan": "137",
    "Alasande Gram": "281",
    "Almond(Badam)": "325",
    "Alsandikai": "166",
    "Amaranthus": "86",
    "Ambada Seed": "130",
    "Ambady/Mesta": "417",
    "Amla(Nelli Kai)": "355",
    "Amphophalus": "102",
    "Amranthas Red": "419",
    "Antawala": "209",
    "Anthorium": "379",
    "Apple": "17",
    "Apricot(Jardalu/Khumani)": "326",
    "Arecanut(Betelnut/Supari)": "140",
    "Arhar (Tur/Red Gram)(Whole)": "49",
    "Arhar Dal(Tur Dal)": "260",
    "Asalia": "444",
    "Asgand": "505",
    "Ashgourd": "83",
    "Ashoka": "506",
    "Ashwagandha": "443",
    "Asparagus": "434",
    "Astera": "232",
    "Atis": "507",
    "Avare Dal": "269",
    "Bael": "418",
    "Bajji chilli": "491",
    "Bajra(Pearl Millet/Cumbu)": "28",
    "Balekai": "274",
    "balsam": "482",
    "Bamboo": "204",
    "Banana": "19",
    "Banana - Green": "90",
    "Banana flower": "483",
    "Banana Leaf": "485",
    "Banana stem": "484",
    "Barley (Jau)": "29",
    "basil": "435",
    "Bay leaf (Tejpatta)": "321",
    "Beans": "94",
    "Beaten Rice": "262",
    "Beetroot": "157",
    "Behada": "508",
    "Bengal Gram Dal (Chana Dal)": "263",
    "Bengal Gram(Gram)(Whole)": "6",
    "Ber(Zizyphus/Borehannu)": "357",
    "Betal Leaves": "143",
    "Betelnuts": "41",
    "Bhindi(Ladies Finger)": "85",
    "Bhui Amlaya": "448",
    "Big Gram": "113",
    "Binoula": "51",
    "Bitter gourd": "81",
    "Black Gram (Urd Beans)(Whole)": "8",
    "Black Gram Dal (Urd Dal)": "264",
    "Black pepper": "38",
    "BOP": "380",
    "Borehannu": "189",
    "Bottle gourd": "82",
    "Brahmi": "449",
    "Bran": "290",
    "Bread Fruit": "497",
    "Brinjal": "35",
    "Brocoli": "487",
    "Broken Rice": "293",
    "Broomstick(Flower Broom)": "320",
    "Bull": "214",
    "Bullar": "284",
    "Bunch Beans": "224",
    "Butter": "272",
    "buttery": "416",
    "Cabbage": "154",
    "Calendula": "480",
    "Calf": "215",
    "Camel Hair": "354",
    "Cane": "205",
    "Capsicum": "164",
    "Cardamoms": "40",
    "Carnation": "375",
    "Carrot": "153",
    "Cashew Kernnel": "238",
    "Cashewnuts": "36",
    "Castor Oil": "270",
    "Castor Seed": "123",
    "Cauliflower": "34",
    "Chakotha": "188",
    "Chandrashoor": "438",
    "Chapparad Avare": "169",
    "Chennangi (Whole)": "241",
    "Chennangi Dal": "295",
    "Cherry": "328",
    "Chikoos(Sapota)": "71",
    "Chili Red": "26",
    "Chilly Capsicum": "88",
    "Chironji": "509",
    "Chow Chow": "167",
    "Chrysanthemum": "402",
    "Chrysanthemum(Loose)": "231",
    "Cinamon(Dalchini)": "316",
    "cineraria": "467",
    "Clarkia": "478",
    "Cloves": "105",
    "Cluster beans": "80",
    "Coca": "315",
    "Cock": "368",
    "Cocoa": "104",
    "Coconut": "138",
    "Coconut Oil": "266",
    "Coconut Seed": "112",
    "Coffee": "45",
    "Colacasia": "318",
    "Copra": "129",
    "Coriander(Leaves)": "43",
    "Corriander seed": "108",
    "Cossandra": "472",
    "Cotton": "15",
    "Cotton Seed": "99",
    "Cow": "212",
    "Cowpea (Lobia/Karamani)": "92",
    "Cowpea(Veg)": "89",
    "Cucumbar(Kheera)": "159",
    "Cummin Seed(Jeera)": "42",
    "Curry Leaf": "486",
    "Custard Apple (Sharifa)": "352",
    "Daila(Chandni)": "382",
    "Dal (Avare)": "91",
    "Dalda": "273",
    "Delha": "410",
    "Dhaincha": "69",
    "dhawai flowers": "442",
    "dianthus": "476",
    "Double Beans": "492",
    "Dragon fruit": "495",
    "dried mango": "423",
    "Drumstick": "168",
    "Dry Chillies": "132",
    "Dry Fodder": "345",
    "Dry Grapes": "278",
    "Duck": "370",
    "Duster Beans": "163",
    "Egg": "367",
    "Egypian Clover(Barseem)": "361",
    "Elephant Yam (Suran)": "296",
    "Field Pea": "64",
    "Fig(Anjura/Anjeer)": "221",
    "Firewood": "206",
    "Fish": "366",
    "Flax seeds": "510",
    "Flower Broom": "365",
    "Foxtail Millet(Navane)": "121",
    "French Beans (Frasbean)": "298",
    "Galgal(Lemon)": "350",
    "Gamphrena": "471",
    "Garlic": "25",
    "Ghee": "249",
    "Giloy": "452",
    "Gingelly Oil": "276",
    "Ginger(Dry)": "27",
    "Ginger(Green)": "103",
    "Gladiolus Bulb": "364",
    "Gladiolus Cut Flower": "363",
    "Glardia": "462",
    "Goat": "219",
    "Goat Hair": "353",
    "golden rod": "475",
    "Gond": "511",
    "Goose berry (Nellikkai)": "494",
    "Gram Raw(Chholia)": "359",
    "Gramflour": "294",
    "Grapes": "22",
    "Green Avare (W)": "165",
    "Green Chilli": "87",
    "Green Fodder": "346",
    "Green Gram (Moong)(Whole)": "9",
    "Green Gram Dal (Moong Dal)": "265",
    "Green Peas": "50",
    "Ground Nut Oil": "267",
    "Ground Nut Seed": "268",
    "Groundnut": "10",
    "Groundnut (Split)": "314",
    "Groundnut pods (raw)": "312",
    "Guar": "75",
    "Guar Seed(Cluster Beans Seed)": "413",
    "Guava": "185",
    "Gudmar": "453",
    "Guggal": "454",
    "gulli": "461",
    "Gur(Jaggery)": "74",
    "Gurellu": "279",
    "gypsophila": "469",
    "Haralekai": "252",
    "Harrah": "512",
    "He Buffalo": "216",
    "Heliconia species": "474",
    "Hen": "369",
    "Hippe Seed": "125",
    "Honey": "236",
    "Honge seed": "124",
    "Hybrid Cumbu": "119",
    "hydrangea": "473",
    "Indian Beans (Seam)": "299",
    "Indian Colza(Sarson)": "344",
    "Irish": "465",
    "Isabgul (Psyllium)": "256",
    "Jack Fruit": "182",
    "Jaee": "513",
    "Jaffri": "406",
    "Jaggery": "151",
    "Jamamkhan": "175",
    "Jamun(Narale Hannu)": "184",
    "Jarbara": "376",
    "Jasmine": "229",
    "Javi": "250",
    "Jowar(Sorghum)": "5",
    "Jute": "16",
    "Jute Seed": "210",
    "Kabuli Chana(Chickpeas-White)": "362",
    "Kacholam": "317",
    "Kakada": "230",
    "kakatan": "501",
    "Kalihari": "456",
    "Kalmegh": "457",
    "Kankambra": "233",
    "Karamani": "115",
    "karanja seeds": "439",
    "Karbuja(Musk Melon)": "187",
    "Kartali (Kantola)": "305",
    "Kevda": "481",
    "Kharif Mash": "61",
    "Khirni": "514",
    "Khoya": "372",
    "Kinnow": "336",
    "Knool Khol": "177",
    "Kodo Millet(Varagu)": "117",
    "kokum": "458",
    "Kooth": "459",
    "Kuchur": "243",
    "Kulthi(Horse Gram)": "114",
    "Kutki": "415",
    "kutki": "426",
    "Ladies Finger": "155",
    "Laha": "515",
    "Lak(Teora)": "96",
    "Leafy Vegetable": "171",
    "Lemon": "310",
    "Lentil (Masur)(Whole)": "63",
    "Lilly": "378",
    "Lime": "180",
    "Limonia (status)": "470",
    "Linseed": "67",
    "Lint": "280",
    "liquor turmeric": "432",
    "Litchi": "351",
    "Little gourd (Kundru)": "302",
    "Long Melon(Kakri)": "304",
    "Lotus": "403",
    "Lotus Sticks": "339",
    "Lukad": "337",
    "Lupine": "479",
    "Ma.Inji": "504",
    "Mace": "107",
    "macoy": "427",
    "Mahedi": "411",
    "Mahua": "335",
    "Mahua Seed(Hippe seed)": "371",
    "Maida Atta": "288",
    "Maize": "4",
    "Mango": "20",
    "Mango (Raw-Ripe)": "172",
    "mango powder": "422",
    "Maragensu": "225",
    "Marasebu": "181",
    "Marget": "407",
    "Marigold(Calcutta)": "235",
    "Marigold(loose)": "405",
    "Marikozhunthu": "502",
    "Mash": "60",
    "Mashrooms": "340",
    "Masur Dal": "259",
    "Mataki": "93",
    "Methi Seeds": "47",
    "Methi(Leaves)": "46",
    "Millets": "237",
    "Mint(Pudina)": "360",
    "Moath Dal": "258",
    "Moath Dal": "95",
    "Mousambi(Sweet Lime)": "77",
    "Muesli": "446",
    "Muleti": "428",
    "Muskmelon Seeds": "516",
    "Mustard": "12",
    "Mustard Oil": "324",
    "Myrobolan(Harad)": "142",
    "Nargasi": "245",
    "Nearle Hannu": "222",
    "Neem Seed": "126",
    "Nelli Kai": "223",
    "Nerium": "500",
    "nigella seeds": "445",
    "nigella seeds": "424",
    "Niger Seed (Ramtil)": "98",
    "Nutmeg": "106",
    "Onion": "23",
    "Onion Green": "358",
    "Orange": "18",
    "Orchid": "381",
    "Other green and fresh vegetables": "420",
    "Other Pulses": "97",
    "Ox": "213",
    "Paddy(Dhan)(Basmati)": "414",
    "Paddy(Dhan)(Common)": "2",
    "Palash flowers": "441",
    "Papaya": "72",
    "Papaya (Raw)": "313",
    "Patti Calcutta": "404",
    "Peach": "331",
    "Pear(Marasebu)": "330",
    "Peas cod": "308",
    "Peas Wet": "174",
    "Peas(Dry)": "347",
    "Pegeon Pea (Arhar Fali)": "301",
    "Pepper garbled": "109",
    "Pepper ungarbled": "110",
    "Perandai": "489",
    "Persimon(Japani Fal)": "327",
    "Pigs": "220",
    "Pineapple": "21",
    "pippali": "431",
    "Plum": "329",
    "Pointed gourd (Parval)": "303",
    "Polherb": "240",
    "Pomegranate": "190",
    "Poppy capsules": "425",
    "poppy seeds": "421",
    "Potato": "24",
    "Pumpkin": "84",
    "Pundi": "254",
    "Pundi Seed": "128",
    "Pupadia": "447",
    "Raddish": "161",
    "Ragi (Finger Millet)": "30",
    "Raibel": "409",
    "Rajgir": "248",
    "Rala": "517",
    "Ram": "282",
    "Ramphal": "518",
    "Rat Tail Radish (Mogari)": "307",
    "Ratanjot": "460",
    "Raya": "65",
    "Rayee": "519",
    "Red Cabbage": "493",
    "Red Gram": "7",
    "Resinwood": "322",
    "Riccbcan": "62",
    "Rice": "3",
    "Ridgeguard(Tori)": "160",
    "Rose(Local)": "374",
    "Rose(Loose))": "228",
    "Rose(Tata)": "373",
    "Round gourd": "306",
    "Rubber": "111",
    "Sabu Dan": "291",
    "Safflower": "59",
    "Saffron": "338",
    "Sajje": "271",
    "salvia": "468",
    "Same/Savi": "122",
    "sanay": "433",
    "Sandalwood": "450",
    "Sarasum": "247",
    "Season Leaves": "277",
    "Seegu": "253",
    "Seemebadnekai": "176",
    "Seetapal": "201",
    "Sesamum(Sesame,Gingelly,Til)": "11",
    "sevanti": "464",
    "She Buffalo": "217",
    "She Goat": "283",
    "Sheep": "218",
    "Siddota": "183",
    "Siru Kizhagu": "490",
    "Skin And Hide": "226",
    "Snakeguard": "156",
    "Soanf": "135",
    "Soapnut(Antawala/Retha)": "207",
    "Soha": "520",
    "Soji": "286",
    "Sompu": "246",
    "Soyabean": "13",
    "spikenard": "455",
    "Spinach": "342",
    "Sponge gourd": "311",
    "Squash(Chappal Kadoo)": "332",
    "stevia": "440",
    "stone pulverizer": "430",
    "Sugar": "48",
    "Sugarcane": "150",
    "Sundaikai": "488",
    "Sunflower": "14",
    "Sunflower Seed": "285",
    "Sunhemp": "139",
    "Suram": "242",
    "Surat Beans (Papadi)": "300",
    "Suva (Dill Seed)": "255",
    "Suvarna Gadde": "178",
    "Sweet Potato": "152",
    "Sweet Pumpkin": "173",
    "Sweet Sultan": "466",
    "sweet william": "477",
    "T.V. Cumbu": "120",
    "Tamarind Fruit": "261",
    "Tamarind Seed": "208",
    "Tapioca": "100",
    "Tinda": "349",
    "Tobacco": "141",
    "Tomato": "78",
    "Torchwood": "323",
    "Toria": "66",
    "Tube Flower": "234",
    "Tube Rose(Double)": "401",
    "Tube Rose(Loose)": "408",
    "Tube Rose(Single)": "377",
    "Tulasi": "503",
    "tulip": "463",
    "Turmeric": "39",
    "Turmeric (raw)": "309",
    "Turnip": "341",
    "vadang": "436",
    "Vatsanabha": "437",
    "Walnut": "343",
    "Water Apple": "496",
    "Water chestnut": "521",
    "Water Melon": "73",
    "Wax": "522",
    "Wheat": "1",
    "Wheat Atta": "287",
    "White Muesli": "429",
    "White Peas": "412",
    "White Pumpkin": "158",
    "Wild lemon": "498",
    "Wood": "203",
    "Wood Apple": "499",
    "Wool": "348",
    "Yam": "244",
    "Yam (Ratalu)": "297"
}

state_map = {
    "Andaman and Nicobar": "AN",
    "Andhra Pradesh": "AP",
    "Arunachal Pradesh": "AR",
    "Assam": "AS",
    "Bihar": "BI",
    "Chandigarh": "CH",
    "Chattisgarh": "CG",
    "Dadra and Nagar Haveli": "DN",
    "Daman and Diu": "DD",
    "Goa": "GO",
    "Gujarat": "GJ",
    "Haryana": "HR",
    "Himachal Pradesh": "HP",
    "Jammu and Kashmir": "JK",
    "Jharkhand": "JR",
    "Karnataka": "KK",
    "Kerala": "KL",
    "Lakshadweep": "LD",
    "Madhya Pradesh": "MP",
    "Maharashtra": "MH",
    "Manipur": "MN",
    "Meghalaya": "MG",
    "Mizoram": "MZ",
    "Nagaland": "NG",
    "NCT of Delhi": "DL",
    "Odisha": "OR",
    "Pondicherry": "PC",
    "Punjab": "PB",
    "Rajasthan": "RJ",
    "Sikkim": "SK",
    "Tamil Nadu": "TN",
    "Telangana": "TL",
    "Tripura": "TR",
    "Uttar Pradesh": "UP",
    "Uttrakhand": "UC",
    "West Bengal": "WB"
}


districts = {}

districts["AN"] = {
    "Nicobar": 2,
    "North and Middle Andaman": 3,
    "South Andaman": 1
}


districts["AP"] = {
    "Anantapur": 12,
    "Chittor": 13,
    "Cuddapah": 1,
    "East Godavari": 14,
    "Guntur": 15,
    "Krishna": 16,
    "Kurnool": 17,
    "Nellore": 18,
    "Prakasam": 19,
    "Srikakulam": 21,
    "Vijayanagaram": 9,
    "Visakhapatnam": 22,
    "West Godavari": 23
}


districts["AR"] = {
    "Changlang": 2,
    "East Kameng": 4,
    "East Siang": 5,
    "Kurung Kummey": 15,
    "Lohit": 7,
    "Lower Dibang Valley": 3,
    "Lower Subansiri": 6,
    "Papum Pore": 1,
    "Tawang": 9,
    "Tirap": 10,
    "Upper Siang": 14,
    "Upper Subansiri": 11,
    "West Kameng": 12,
    "West Siang": 13
}

districts["AS"] = {
    "Barpeta": 5,
    "BONGAIGAON": 4,
    "Cachar": 6,
    "Darrang": 1,
    "Dhemaji": 7,
    "Dhubri": 2,
    "Dibrugarh": 9,
    "Goalpara": 10,
    "Golaghat": 11,
    "Hailakandi": 12,
    "Jorhat": 13,
    "Kamrup": 3,
    "Karbi Anglong": 8,
    "Karimganj": 14,
    "Kokrajhar": 15,
    "Lakhimpur": 16,
    "Mangaldoi": 17,
    "MORIGAON": 18,
    "Nagaon": 19,
    "Nalbari": 20,
    "North Cachar Hills": 21,
    "Sibsagar": 22,
    "Sonitpur": 23,
    "Tinsukia": 24
}
districts["BI"] = {
    "Araria": 19,
    "Arwal": 94,
    "Aurangabad": 20,
    "Banka": 21,
    "Begusarai": 1,
    "Bhagalpur": 2,
    "Bhojpur": 23,
    "Buxar": 25,
    "Chhapra": 55,
    "Darbhanga": 4,
    "East Champaran/ Motihari": 26,
    "Gaya": 9,
    "Gopalgang": 30,
    "Jamui": 32,
    "Jehanabad": 33,
    "Kaimur/Bhabhua": 96,
    "Kaithar": 11,
    "Khagaria": 34,
    "Kishanganj": 35,
    "Luckeesarai": 52,
    "Madhepura": 38,
    "Madhubani": 12,
    "Munghair": 39,
    "Muzaffarpur": 13,
    "Nalanda": 40,
    "Nawada": 41,
    "Patna": 14,
    "Purnea": 15,
    "Rohtas": 17,
    "Saharsa": 44,
    "Samastipur": 46,
    "Saran": 47,
    "Sheikhpura": 53,
    "Sheohar": 54,
    "Sitamarhi": 48,
    "Siwan": 18,
    "Supaul": 49,
    "Vaishali": 50,
    "West Chambaran": 51
}
districts["CH"] = {
    "Chandigarh": 1
}
districts["CG"] = {
    "Balod": 52,
    "Balodabazar": 50,
    "Balrampur": 55,
    "Bastar": 18,
    "Bemetara": 49,
    "Bijapur": 16,
    "Bilaspur": 21,
    "Dantewada": 1,
    "Dhamtari": 3,
    "Durg": 26,
    "Gariyaband": 51,
    "Jagdalpur": 12,
    "Janjgir": 8,
    "Jashpur": 2,
    "Kabirdham": 13,
    "Kanker": 4,
    "Kawardha": 5,
    "Kondagaon": 56,
    "Korba": 6,
    "Koria": 7,
    "Mahasamund": 9,
    "Mungeli": 53,
    "Narayanpur": 14,
    "North Bastar": 15,
    "Raigarh": 36,
    "Raipur": 10,
    "Rajnandgaon": 11,
    "Sukma": 48,
    "Surajpur": 54,
    "Surguja": 47
}
districts["DN"] = {
    "Dadra & Nagar Haveli": 1,
    "Silvassa": 2
}
districts["DD"] = {
    "Daman": 1,
    "Diu": 2
}
districts["GO"] = {
    "North Goa": 2,
    "South Goa": 1
}
districts["GJ"] = {
    "Ahmedabad": 1,
    "Amreli": 15,
    "Anand": 2,
    "Aravalli": 32,
    "Banaskanth": 3,
    "Bharuch": 5,
    "Bhavnagar": 6,
    "Botad": 28,
    "Chhota Udaipur": 29,
    "Dahod": 7,
    "Dang": 33,
    "Devbhumi Dwarka": 35,
    "Gandhinagar": 17,
    "Gir Somnath": 30,
    "Jamnagar": 18,
    "Junagarh": 19,
    "Kachchh": 20,
    "Kheda": 8,
    "Mahisagar": 31,
    "Mehsana": 9,
    "Morbi": 27,
    "Narmada": 24,
    "Navsari": 25,
    "Panchmahals": 21,
    "Patan": 10,
    "Porbandar": 26,
    "Rajkot": 11,
    "Sabarkantha": 12,
    "Surat": 13,
    "Surendranagar": 14,
    "Tapi": 34,
    "The Dangs": 16,
    "Vadodara(Baroda)": 4,
    "Valsad": 23
}
districts["HR"] = {
    "Ambala": 1,
    "Bhiwani": 10,
    "Faridabad": 2,
    "Fatehabad": 3,
    "Gurgaon": 11,
    "Hissar": 4,
    "Jhajar": 19,
    "Jind": 5,
    "Kaithal": 6,
    "Karnal": 7,
    "Kurukshetra": 8,
    "Mahendragarh-Narnaul": 12,
    "Mewat": 20,
    "Palwal": 21,
    "Panchkula": 13,
    "Panipat": 14,
    "Rewari": 15,
    "Rohtak": 16,
    "Sirsa": 9,
    "Sonipat": 17,
    "Yamuna Nagar": 18
}
districts["HP"] = {
    "Bilaspur": 5,
    "Chamba": 6,
    "Hamirpur": 7,
    "Kangra": 1,
    "Kangra (at Dharmashala)": 8,
    "Kinnaur (at Kalpa)": 9,
    "Kullu": 2,
    "Lahul & Spiti": 11,
    "Mandi": 12,
    "Shimla": 13,
    "Sirmore": 3,
    "Solan": 4,
    "Una": 15
}
districts["JK"] = {
    "Anantnag": 1,
    "Badgam": 7,
    "Bandipora": 87,
    "Baramulla": 2,
    "Doda": 8,
    "Ganderbal": 88,
    "Jammu": 3,
    "Kargil": 9,
    "Kathua": 10,
    "Kishtwar": 91,
    "Kulgam": 89,
    "Kupwara": 11,
    "Leh": 12,
    "Poonch": 13,
    "Pulwama": 4,
    "Rajouri": 15,
    "Ramban": 92,
    "Samba": 93,
    "Shopian": 90,
    "Srinagar": 5,
    "Udhampur": 6
}
districts["JR"] = {
    "Bokaro": 24,
    "Chatra": 53,
    "Deogarh": 5,
    "Dhanbad": 6,
    "Dumka": 7,
    "East Singhbhum": 8,
    "Garhwa": 27,
    "Giridih": 29,
    "Godda": 28,
    "Gumla": 31,
    "Hazaribagh": 10,
    "Jamtara": 18,
    "Koderma": 36,
    "Latehar": 17,
    "Lohardaga": 37,
    "Pakur": 42,
    "Palamu": 43,
    "Ranchi": 16,
    "Sahebgang": 45,
    "Saraikela(Kharsanwa)": 19,
    "Simdega": 1,
    "West Singbhum": 52
}
districts["KK"] = {
    "Bagalkot": 25,
    "Bangalore": 1,
    "Belgaum": 2,
    "Bellary": 3,
    "Bidar": 4,
    "Bijapur": 5,
    "Chamrajnagar": 28,
    "Chikmagalur": 15,
    "Chitradurga": 16,
    "Davangere": 6,
    "Dharwad": 7,
    "Gadag": 27,
    "Hassan": 18,
    "Haveri": 8,
    "Kalburgi": 17,
    "Karwar(Uttar Kannad)": 19,
    "Kolar": 10,
    "Koppal": 11,
    "Madikeri(Kodagu)": 20,
    "Mandya": 21,
    "Mangalore(Dakshin Kannad)": 22,
    "Mysore": 12,
    "Raichur": 14,
    "Ramanagar": 29,
    "Shimoga": 23,
    "Tumkur": 24,
    "Udupi": 26,
    "Yadgiri": 30
}
districts["KL"] = {
    "Alappuzha": 16,
    "Alleppey": 1,
    "Calicut": 2,
    "Ernakulam": 3,
    "Idukki": 13,
    "Kannur": 4,
    "Kasargod": 14,
    "Kollam": 5,
    "Kottayam": 6,
    "Kozhikode(Calicut)": 7,
    "Malappuram": 8,
    "Palakad": 9,
    "Pathanamthitta": 15,
    "Thirssur": 11,
    "Thiruvananthapuram": 10,
    "Wayanad": 12
}
districts["LD"] = {
    "Kavaratti": 1
}
districts["MP"] = {
    "Agar Malwa": 62,
    "Alirajpur": 59,
    "Anupur": 58,
    "Ashoknagar": 57,
    "Badwani": 56,
    "Balaghat": 17,
    "Betul": 19,
    "Bhind": 20,
    "Bhopal": 1,
    "Burhanpur": 60,
    "Chhatarpur": 22,
    "Chhindwara": 23,
    "Damoh": 24,
    "Datia": 49,
    "Dewas": 2,
    "Dhar": 50,
    "Dindori": 51,
    "Guna": 4,
    "Gwalior": 5,
    "Harda": 52,
    "Hoshangabad": 27,
    "Indore": 6,
    "Jabalpur": 7,
    "Jhabua": 28,
    "Katni": 53,
    "Khandwa": 29,
    "Khargone": 30,
    "Mandla": 31,
    "Mandsaur": 32,
    "Morena": 33,
    "Narsinghpur": 34,
    "Neemuch": 9,
    "Panna": 35,
    "Raisen": 37,
    "Rajgarh": 38,
    "Ratlam": 39,
    "Rewa": 40,
    "Sagar": 41,
    "Satna": 13,
    "Sehore": 16,
    "Seoni": 43,
    "Shajapur": 12,
    "Shehdol": 44,
    "Sheopur": 54,
    "Shivpuri": 45,
    "Sidhi": 46,
    "Singroli": 61,
    "Tikamgarh": 48,
    "Ujjain": 14,
    "Umariya": 55,
    "Vidisha": 15
}
districts["MH"] = {
    "Ahmednagar": 1,
    "Akola": 2,
    "Amarawati": 3,
    "Bandra(E)": 20,
    "Beed": 21,
    "Bhandara": 22,
    "Buldhana": 4,
    "Chandrapur": 23,
    "Chattrapati Sambhajinagar": 19,
    "Dharashiv(Usmanabad)": 26,
    "Dhule": 5,
    "Gadchiroli": 24,
    "Gondiya": 34,
    "Hingoli": 35,
    "Jalana": 6,
    "Jalgaon": 7,
    "Kolhapur": 8,
    "Latur": 9,
    "Mumbai": 10,
    "Murum": 37,
    "Nagpur": 11,
    "Nanded": 25,
    "Nandurbar": 12,
    "Nashik": 13,
    "Osmanabad": 36,
    "Parbhani": 27,
    "Pune": 14,
    "Raigad": 28,
    "Ratnagiri": 29,
    "Sangli": 15,
    "Satara": 30,
    "Sholapur": 16,
    "Sindhudurg": 31,
    "Thane": 17,
    "Vashim": 33,
    "Wardha": 18,
    "Yavatmal": 32
}
districts["MN"] = {
    "Bishnupur": 2,
    "Chandel": 3,
    "Churachandpur": 4,
    "Imphal East": 9,
    "Imphal West": 1,
    "Kakching": 11,
    "Senapati": 5,
    "Tamenglong": 6,
    "Tengnoupal": 10,
    "Thoubal": 7,
    "Ukhrul": 8
}
districts["MG"] = {
    "East Garo Hills": 2,
    "East Jaintia Hills": 8,
    "East Khasi Hills": 1,
    "Nongpoh (R-Bhoi)": 4,
    "North Garo Hills": 11,
    "South Garo Hills": 5,
    "South West Garo Hills": 9,
    "South West Khasi Hills": 10,
    "West Garo Hills": 6,
    "West Jaintia Hills": 3,
    "West Khasi Hills": 7
}
districts["DL"] = {
    "Delhi": 1
}
districts["OR"] = {
    "Angul": 1,
    "Balasore": 16,
    "Bargarh": 2,
    "Berhampur": 38,
    "Bhadrak": 3,
    "Bhubaneswar": 39,
    "Bolangir": 4,
    "Boudh": 26,
    "Cuttack": 5,
    "Deogarh": 27,
    "Dhenkanal": 17,
    "Gajapati": 28,
    "Ganjam": 18,
    "Jagatsinghpur": 29,
    "Jajpur": 7,
    "Jharsuguda": 30,
    "Kalahandi": 8,
    "Kandhamal": 9,
    "Kendrapara": 31,
    "Keonjhar": 19,
    "Khurda": 32,
    "Koraput": 10,
    "Malkangiri": 33,
    "Mayurbhanja": 20,
    "Nayagarh": 35,
    "Nowarangpur": 12,
    "Nuapada": 34,
    "Puri": 13,
    "Rayagada": 14,
    "Rourkela": 37,
    "Sambalpur": 22,
    "Sonepur": 36,
    "Sundergarh": 23
}
districts["PC"] = {
    "Karaikal": 4,
    "Mahe": 2,
    "Pondicherry": 1,
    "Yanam": 3
}
districts["PB"] = {
    "Amritsar": 1,
    "Barnala": 20,
    "Bhatinda": 11,
    "Faridkot": 2,
    "Fatehgarh": 12,
    "Fazilka": 21,
    "Ferozpur": 3,
    "Gurdaspur": 4,
    "Hoshiarpur": 13,
    "Jalandhar": 14,
    "kapurthala": 5,
    "Ludhiana": 6,
    "Mansa": 15,
    "Moga": 7,
    "Mohali": 19,
    "Muktsar": 8,
    "Nawanshahr": 17,
    "Pathankot": 22,
    "Patiala": 9,
    "Ropar (Rupnagar)": 16,
    "Sangrur": 10,
    "Tarntaran": 18
}
districts["RJ"] = {
    "Jhunjhunu": 14,
    "Ajmer": 1,
    "Alwar": 2,
    "Anupgarh": 51,
    "Balotra": 44,
    "Banswara": 19,
    "Baran": 3,
    "Barmer": 20,
    "Beawar": 37,
    "Bharatpur": 4,
    "Bhilwara": 5,
    "Bikaner": 21,
    "Bundi": 6,
    "Chittorgarh": 7,
    "Churu": 8,
    "Dausa": 10,
    "Deedwana Kuchaman": 49,
    "Deeg": 40,
    "Dholpur": 22,
    "Dudu": 36,
    "Dungarpur": 23,
    "Ganganagar": 11,
    "Gangapur City": 48,
    "Hanumangarh": 12,
    "Jaipur": 13,
    "Jaipur Rural": 43,
    "Jaisalmer": 24,
    "Jalore": 25,
    "Jhalawar": 26,
    "Jodhpur": 15,
    "Jodhpur Rural": 45,
    "Karauli": 33,
    "Kekri": 38,
    "Khairthal Tijara": 41,
    "Kota": 16,
    "Kotputli- Behror": 42,
    "Nagaur": 17,
    "Neem Ka Thana": 50,
    "Pali": 27,
    "Phalodi": 46,
    "Pratapgarh": 35,
    "Rajsamand": 28,
    "Sanchore": 47,
    "Shahpura": 39,
    "Sikar": 29,
    "Sirohi": 30,
    "Swai Madhopur": 18,
    "Tonk": 31,
    "Udaipur": 32
}
districts["SK"] = {
    "East": 1,
    "North Sikkim (Mangan)": 2,
    "South Sikkim (Namchi)": 3,
    "West Sikkim (Gyalsing)": 4
}
districts["TN"] = {
    "Ariyalur": 30,
    "Chengalpattu": 32,
    "Chennai": 15,
    "Coimbatore": 1,
    "Cuddalore": 2,
    "Dharmapuri": 12,
    "Dindigul": 13,
    "Erode": 3,
    "Kallakuruchi": 33,
    "Kancheepuram": 4,
    "Karur": 14,
    "Krishnagiri": 31,
    "Madurai": 5,
    "Mayiladuthurai": 38,
    "Nagapattinam": 16,
    "Nagercoil (Kannyiakumari)": 17,
    "Namakkal": 18,
    "Perambalur": 6,
    "Pudukkottai": 20,
    "Ramanathapuram": 21,
    "Ranipet": 34,
    "Salem": 22,
    "Sivaganga": 23,
    "Tenkasi": 35,
    "Thanjavur": 7,
    "The Nilgiris": 19,
    "Theni": 24,
    "Thiruchirappalli": 25,
    "Thirunelveli": 26,
    "Thirupathur": 36,
    "Thirupur": 37,
    "Thiruvannamalai": 8,
    "Thiruvarur": 9,
    "Thiruvellore": 27,
    "Tuticorin": 28,
    "Vellore": 29,
    "Villupuram": 10,
    "Virudhunagar": 11
}
districts["TL"] = {
    "Adilabad": 11,
    "Hyderabad": 2,
    "Jagityal": 21,
    "Kamareddy": 23,
    "Karimnagar": 3,
    "Khammam": 4,
    "Mahbubnagar": 5,
    "Medak": 6,
    "Nalgonda": 7,
    "Nizamabad": 8,
    "Ranga Reddy": 20,
    "Siddipet": 22,
    "Warangal": 10
}
districts["TR"] = {
    "Dhalai": 3,
    "Gomati": 8,
    "Khowai": 7,
    "North Tripura": 4,
    "Sepahijala": 5,
    "South District": 1,
    "Unokoti": 6,
    "West District": 2
}
districts["UP"] = {
    "Agra": 1,
    "Aligarh": 31,
    "Ambedkarnagar": 33,
    "Amethi": 66,
    "Amroha": 80,
    "Auraiya": 73,
    "Ayodhya": 8,
    "Azamgarh": 34,
    "Badaun": 35,
    "Baghpat": 74,
    "Bahraich": 3,
    "Ballia": 4,
    "Balrampur": 75,
    "Banda": 36,
    "Barabanki": 5,
    "Bareilly": 6,
    "Basti": 37,
    "Bhadohi(Sant Ravi Nagar)": 38,
    "Bijnor": 39,
    "Bulandshahar": 40,
    "Chandauli": 76,
    "Chitrakut": 77,
    "Deoria": 42,
    "Etah": 43,
    "Etawah": 14,
    "Farukhabad": 9,
    "Fatehpur": 44,
    "Firozabad": 45,
    "Gautam Budh Nagar": 78,
    "Ghaziabad": 10,
    "Ghazipur": 47,
    "Gonda": 48,
    "Gorakhpur": 11,
    "Hamirpur": 49,
    "Hardoi": 13,
    "Hathras": 79,
    "Jalaun (Orai)": 51,
    "Jaunpur": 15,
    "Jhansi": 52,
    "Kannuj": 81,
    "Kanpur": 16,
    "Kanpur Dehat": 87,
    "Kasganj": 88,
    "Kaushambi": 82,
    "Khiri (Lakhimpur)": 85,
    "Kushinagar": 59,
    "Lakhimpur": 17,
    "Lalitpur": 18,
    "Lucknow": 19,
    "Maharajganj": 53,
    "Mahoba": 54,
    "Mainpuri": 20,
    "Mathura": 55,
    "Mau(Maunathbhanjan)": 56,
    "Meerut": 21,
    "Mirzapur": 57,
    "Muzaffarnagar": 58,
    "Oraya": 86,
    "Pillibhit": 24,
    "Pratapgarh": 61,
    "Prayagraj": 2,
    "Raebarelli": 62,
    "Rampur": 63,
    "Saharanpur": 25,
    "Sambhal": 22,
    "Sant Kabir Nagar": 83,
    "Shahjahanpur": 26,
    "Shamli": 89,
    "Shravasti": 84,
    "Siddharth Nagar": 64,
    "Sitapur": 27,
    "Sonbhadra": 65,
    "Unnao": 68,
    "Varanasi": 30
}
districts["UK"] = {
    "Almora": 32,
    "Bageshwar": 70,
    "Chamoli (Gopeshwar)": 41,
    "Champawat": 71,
    "Dehradoon": 7,
    "Garhwal (Pauri)": 46,
    "Haldwani": 1,
    "Haridwar": 50,
    "Nanital": 23,
    "Pithoragarh": 60,
    "Rudraprayag": 72,
    "Tehri Garhwal": 67,
    "UdhamSinghNagar": 28,
    "Uttarkashi": 69
}
districts["WB"] = {
    "Alipurduar": 20,
    "Bankura": 2,
    "Birbhum": 3,
    "Burdwan": 4,
    "Coochbehar": 5,
    "Dakshin Dinajpur": 6,
    "Darjeeling": 17,
    "Hooghly": 7,
    "Howrah": 18,
    "Jalpaiguri": 8,
    "Jhargram": 21,
    "Kalimpong": 22,
    "Kolkata": 16,
    "Malda": 9,
    "Medinipur(E)": 10,
    "Medinipur(W)": 11,
    "Murshidabad": 12,
    "Nadia": 13,
    "North 24 Parganas": 1,
    "Paschim Bardhaman": 23,
    "Purba Bardhaman": 24,
    "Puruliya": 19,
    "Sounth 24 Parganas": 15,
    "Uttar Dinajpur": 14
}
districts["MZ"]={
    "Aizawl": 1,
    "Kolasib": 5,
    "Lungli": 2,
    "Mamit": 4,
    "Saiha": 3
}
districts["NG"]={
    "Dimapur": 8,
    "Kiphire": 11,
    "Kohima": 1,
    "Longleng": 10,
    "Mokokchung": 3,
    "Mon": 4,
    "Peren": 9,
    "Phek": 2,
    "Tsemenyu": 12,
    "Tuensang": 5,
    "Wokha": 6,
    "Zunheboto": 7
}